name: review
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - invoke=1.4.1
  - ipykernel=5.3.4
  - networkx=2.5
  - pandas=1.1.3
  - pip=20.2.4
  - pip:
    - arcas==1.0
    - bibtexparser==1.2
    - graphviz==0.14.2
