name: review
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - invoke=1.4.1
  - ipykernel=5.3.4
  - matplotlib=3.3.2
  - networkx=2.5
  - pandas=1.1.3
  - pip=20.2.4
  - tqdm=4.50.2
  - pip:
    - git+https://github.com/ArcasProject/Arcas@v1.0.0
    - bibtexparser==1.2
    - graphviz==0.14.2
