""" A set of known words and end-of-word patterns for the spellchecker. """

words = {
    "Cattell",
    "Ciw",
    "Erlang",
    "Kroeber",
    "LCA",
    "NHS",
    "Simul",
    "Sneath",
    "Sokal(|'s)",
    "bibliometric",
    "comorbidit(y|ies)",
    "dataset(|s)",
    "findable",
    "geosciences",
    "interoperable",
    "infographic",
    "iterative(|ly)",
    "parallelised",
    "preprint",
    "preprocessing",
    "priori",
    "reproducib(le|ility)",
    "rostering",
    "scalab(le|ility)",
    "th",
}
