""" A set of known words and end-of-word patterns for the spellchecker. """

words = {
    "bibliometric",
    "cattell",
    "centroid(|s|al)",
    "ciw",
    "comorbidit(y|ies)",
    "dataset(|s)",
    "erlang",
    "findable",
    "geosciences",
    "infographic",
    "interoperable",
    "iterative(|ly)",
    "kroeber",
    "lca",
    "mahalonobis",
    "medoids",
    "nhs",
    "parallelised",
    "preprint",
    "preprocessing",
    "priori",
    "reproducib(le|ility)",
    "rostering",
    "scalab(le|ility)",
    "simul",
    "sneath",
    "sokal(|'s)",
    "th",
    "voronoi",
}
